packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2
  '@hono/node-server': ^1
  '@radix-ui/react-slot': ^1
  '@t3-oss/env-core': ^0
  '@tailwindcss/vite': ^4
  '@tanstack/react-router': ^1
  '@tanstack/react-router-devtools': ^1
  '@tanstack/react-start': ^1
  '@types/node': ^24
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5
  class-variance-authority: ^0
  clsx: ^2
  hono: ^4
  lucide-react: ^0
  react: ^19
  react-dom: ^19
  tailwind-merge: ^3
  tailwindcss: ^4
  tsx: ^4
  turbo: ^2
  tw-animate-css: ^1
  typescript: ^5
  vite: ^7
  vite-tsconfig-paths: ^5
  zod: ^4

onlyBuiltDependencies:
  - esbuild
