packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2
  '@hono/node-server': ^1
  '@tanstack/react-router': ^1
  '@tanstack/react-start': ^1
  '@types/node': 24.9.1
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5
  hono: ^4
  react: ^19
  react-dom: ^19
  tailwindcss: ^4
  turbo: ^2
  tsx: ^4
  typescript: 5.9.2
  vite: ^7
  vite-tsconfig-paths: ^5
