packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2
  '@hono/node-server': ^1
  '@radix-ui/react-slot': 1.2.3
  '@tailwindcss/vite': ^4
  '@tanstack/react-router': ^1
  '@tanstack/react-router-devtools': ^1
  '@tanstack/react-start': ^1
  '@types/node': ^24
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5
  class-variance-authority: ^0
  clsx: ^2
  hono: ^4
  lucide-react: ^0
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwind-merge: ^3
  tailwindcss: ^4.1.16
  tsx: ^4
  turbo: ^2
  tw-animate-css: ^1
  typescript: 5.9.2
  vite: ^7.1.12
  vite-tsconfig-paths: ^5.1.4

onlyBuiltDependencies:
  - esbuild
