packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2
  '@hono/node-server': ^1
  '@tanstack/react-router': ^1
  '@tanstack/react-router-devtools': ^1
  '@tanstack/react-start': ^1
  '@types/node': ^24
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5
  hono: ^4
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwindcss: ^4
  tsx: ^4
  turbo: ^2
  typescript: 5.9.2
  vite: ^7.1.12
  vite-tsconfig-paths: ^5.1.4

onlyBuiltDependencies:
  - esbuild
